### ISSUE TITLE
Home page 

### ISSUE THREAD

**Issue by pbartosova** [ARUP-CAS/aiscr-api-home#1]
https://api-dev.aiscr.cz/
https://api-test.aiscr.cz/
https://api-tr.aiscr.cz/
https://api.aiscr.cz/

Jednoduchá statická stránka s informacemi pro uživatele a odkazem na uživatelskou příručku s příklady užití.

**Comment by vbar** [comment]
OK, takže jsem zkopíroval HTML do tohoto repozitáře (napříště bude autoritativní verze tady) a nasadil na https://api.aiscr.cz (a https://api/test.aiscr.cz ).

**Comment by motyc** [comment]
Finální editaci stránky jsem provedl rovnou zde do html. Stačí tedy změny promítnout na server.

**Comment by vbar** [comment]
OK, nasazeno.
