### ISSUE TITLE
Set up Zenodo archiving

### ISSUE THREAD

**Issue by petrpajdla** [ARUP-CAS/aiscr-api-home#11]
Set up Zenodo archiving.

- [x] CITATION.cff
- [ ] Archive on each release

**Comment by motyc** [comment]
Opraveno na Zenodo :)

**Comment by petrpajdla** [comment]
@motyc GH asi nějak změnil politiku u repozitářů z organizací, potřebuju, abys u organizace povolil Zenodo archivaci, aby se mi repozitář ukázal na Zenodu a mohl jsem povolit archivaci, postup zde:

https://docs.github.com/en/organizations/managing-oauth-access-to-your-organizations-data/approving-oauth-apps-for-your-organization

**Comment by petrpajdla** [comment]
Pomocí souboru `.zenodo.json` jde přidávat metadata specifická pro Zenodo.

https://developers.zenodo.org/#github

**Comment by motyc** [comment]
@petrpajdla Jenže ono to tam povolené je:
![image](https://github.com/user-attachments/assets/d2f9d588-4424-4c48-b429-0de04e40e029)

**Comment by motyc** [comment]
@petrpajdla Zkusil jsem to znovu synchronizovat, znovu to pozapínal a už to snad pojede.

**Comment by motyc** [comment]
@petrpajdla Smazal bych původní release a udělal ho znovu, tím se to tam dostane (tag jde zachovat).

**Comment by petrpajdla** [comment]
Už se to tam ukázalo, jen mi to říká "managed by another user", zkusím smazat release a udělat znovu jak píšeš.
