### ISSUE TITLE
Default branch master > main

### ISSUE THREAD

**Issue by petrpajdla** [ARUP-CAS/aiscr-api-home#9]
Prosím @motyc v Settings v nabídce Default branch nastavit main jako default branch, nebo mi nějak zvýšit práva k repozitáři, díky!

Viz https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/changing-the-default-branch

**Comment by motyc** [comment]
@petrpajdla Udělal jsem oboje, tj. upraven default + jsi nově admin

**Comment by petrpajdla** [comment]
Supr díky.
